# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_services
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_services
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
